### ISSUE TITLE
Processed data available for download?

### ISSUE THREAD

**Issue by MarcElosua** [theislab/2018_Angelidis#3]
Hello!

Thank you for putting together this great study! We would love to reuse this data for an ongoing project in our lab but cannot download it using the [download.sh](https://github.com/theislab/2018_Angelidis/blob/master/download.sh) script. Would it be possible to share the processed data, or at least the annotation of the cells so we don't have to start from the raw files?

Thank you very much!
Marc

**Comment by lkmklsmn** [comment]
Hi,

Unfortunately that link is not valid anymore. Have you checked the files at the [GEO repo](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124872)? The metadata there includes cell type information.

**Comment by MarcElosua** [comment]
Oh perfect, will take a look! Thanks!
